config/routes.rb
Rails.application.routes.draw do
  resources :interviews, except:[:index, :show]
  get "interviews/lawyer_schedule", to: "interviews#lawyer_schedule", as: "lawyer_schedule"
  get "interviews/firm_schedule", to: "interviews#firm_schedule", as: "firm_schedule"
  resources :lawyer_infos
  get "more_info/:id", to: "firm_infos#lawyer_info_restricted", as: "lawyer_info_restricted"
  resources :firm_infos
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  resources :pages
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firm_info.rb
class FirmInfo < ApplicationRecord
  belongs_to :user
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :user
end

app/models/lawyer_info.rb
class LawyerInfo < ApplicationRecord
  belongs_to :user
  mount_uploader :cv, CvUploader
  PRACTICE_AREA = ["Litigation", "Finance", "Corporate", "Employment"]
  JOB_STATUS = ["Actively looking", "Could be tempted", "Not actively looking"]
  PQE = (1...15).to_a
  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :pqe, presence: true
  validates :university, presence: true
  validates :expected_salary, presence: true
  validates :interests, presence: true
  validates :post_code, presence: true

  def self.filter(args)
    job_status = args[:job_status] if args[:job_status].present?
    practice_area = args[:practice_area] if args[:practice_area].present?
    pqe = args[:pqe] if args[:pqe].present?

    return where(job_status: job_status, practice_area: practice_area, pqe: pqe) if job_status && practice_area && pqe
    return where(job_status: job_status, practice_area: practice_area) if job_status && practice_area
    return where(job_status: job_status, pqe: pqe) if job_status && pqe
    return where(practice_area: practice_area, pqe: pqe) if practice_area && pqe
    return where(job_status: job_status) if job_status
    return where(practice_area: practice_area) if practice_area
    return where(pqe: pqe) if pqe
    return all
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :interviews
  has_one :firm_info
  has_one :lawyer_info
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:lawyer])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:lawyer])
    end

    def after_sign_in_path_for(user)
      users_path(user)
    end

end

app/controllers/firm_infos_controller.rb
class FirmInfosController < ApplicationController
  before_action :set_firm_info, only: [:show, :destroy]

  def index
    @lawyer_infos = LawyerInfo.filter(params)
  end

  def show
  end

  def new
    @firm_info = FirmInfo.new
  end

  def create
    @firm_info = FirmInfo.new(firm_info_params)
    @firm_info.user = current_user
    if @firm_info.save
      redirect_to users_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def lawyer_info_restricted
    @interview = Interview.new
    @lawyerinfo = LawyerInfo.find(params[:id])
  end

  private

  def set_firm_info
    @firm_info = FirmInfo.find(params[:id])
  end

  def firm_info_params
    params.require(:firm_info).permit(:first_name, :last_name, :firm_name, :job_title)
  end

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:edit, :destroy, :update]
  def edit
  end

  def update
  end

  def destroy
  end

  # def new
  #   @interview = Interview.new

  # end

  def create
    @interview = Interview.new(interview_params)
    @interview.user = current_user
    if @interview.save

    else
      raise
    end
  end

  def lawyer_schedule
    @interviews = Interview.all
  end

 def firm_schedule
    @interviews = Interview.all
  end

  private

  def set_interview
    @interview = Interview.find(params[:id])
  end

  def interview_params
    params.require(:interview).permit(:date, :time)
  end




end

app/controllers/lawyer_infos_controller.rb
class LawyerInfosController < ApplicationController
  before_action :set_lawyerinfo, only: [:edit, :destroy, :update]
  def index
  end

  def edit
  end

  def show
    @lawyerinfo = LawyerInfo.find_by(user_id: current_user)
  end

  def new
    @lawyerinfo = LawyerInfo.new
  end

  def create
    @lawyerinfo = LawyerInfo.new(lawyerinfo_params)
    @lawyerinfo.user = current_user
    if @lawyerinfo.save
      redirect_to lawyer_schedule_path
    else
      render :new
    end
  end

  def update
    if @lawyerinfo.update(lawyerinfo_params)
      redirect_to lawyer_info_path(@lawyerinfo)
    else
      render :edit
    end
  end

  def destroy
    @lawyerinfo.destroy
    redirect_to lawyer_infos_path, notice: 'Profile was successfully deleted.'
  end


  private

  def set_lawyerinfo
    @lawyerinfo = LawyerInfo.find(params[:id])
  end

  def lawyerinfo_params
    params.require(:lawyer_info).permit(:first_name, :last_name, :current_firm, :job_title, :pqe, :university, :degree_classification, :expected_salary, :job_status, :practice_area, :firm_type, :interests, :post_code, :cv)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    if resource.lawyer
      new_lawyer_info_path
    else
      new_firm_info_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user.lawyer

      redirect_to  lawyer_schedule_path(current_user)
    else

      redirect_to firm_infos_path
    end
  end

  def edit
  end

  def show
  end

  def destroy
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/firm_infos/create.html.erb
<h1>FirmInfos#create</h1>
<p>Find me in app/views/firm_infos/create.html.erb</p>

app/views/firm_infos/destroy.html.erb
<h1>FirmInfos#destroy</h1>
<p>Find me in app/views/firm_infos/destroy.html.erb</p>

app/views/firm_infos/edit.html.erb
<h1>FirmInfos#edit</h1>
<p>Find me in app/views/firm_infos/edit.html.erb</p>

app/views/firm_infos/index.html.erb
<div class="wrapper">
  <div class="all-container">
    <h3 class="text-center">Hi <%= current_user.firm_info.first_name%>, there's <span><%= pluralize @lawyer_infos.count, "lawyer" %> in your current search.</span> Happy recruiting!</h3>
    <div class="main-container">
      <!-- <div class="filter-container-parent"> -->
        <div class="filter-container">

          <%= form_tag firm_infos_path, method: :get do %>

            <h5 >Practice area</h5 >
            <select class="filter-box" name="practice_area">
              <option value="">Department</option>
              <% LawyerInfo::PRACTICE_AREA.each do |info| %>
                 <option value="<%= info %>"><%= info %></option>
              <% end %>
            </select>
            <br>

            <h5 class="h5-title">Job status</h5 >
            <select class="filter-box" name="job_status">
              <option value="">Job status</option>
              <% LawyerInfo::JOB_STATUS.each do |info| %>
                 <option value="<%= info %>"><%= info %></option>
              <% end %>
            </select>
            <br>

            <h5 class="h5-title">Post-qual experience</h5 >
            <select class="filter-box" name="pqe">
              <option value="">PQE</option>
              <% LawyerInfo::PQE.each do |info| %>
                 <option value="<%= info %>"><%= info %></option>
              <% end %>
            </select>
            <br>


            <%= submit_tag value="Apply", :class => "filter-button"%>
          <% end %>
        </div>
      <!-- </div> -->
      <div class="cards-container">

        <% @lawyer_infos.each do |lawyer_info| %>
          <% unless lawyer_info.nil? %>
            <div class="card">
              <div class="card-information">
                <div class="card-info-top">
                  <div class="card-info-title">
                    <h4><%= lawyer_info.job_title %></h4>
                    <p><%= lawyer_info.practice_area %></p>
                  </div>
                  <div class="card-info-tags">
                    <span class="tag"><%= lawyer_info.job_status %></span>
                    <span class="tag">£<%= lawyer_info.expected_salary %></span>
                  </div>
                </div>
                <div class="card-info-bottom">
                  <span>PQE: <%= lawyer_info.pqe %></span>
                  <span>Current firm: <%= lawyer_info.current_firm %></span>
                  <span>University: <%= lawyer_info.university %></span>
                </div>
              </div>
              <div class="btn-more-info">
                <%= link_to "More info" , lawyer_info_restricted_path(lawyer_info), target: :blank %>
                <%= image_tag 'right_arrow_white.png', class: "arrow", width: 28, height: 59 %>
              </div>
            </div>

           <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/firm_infos/lawyer_info_restricted.html.erb
<div class="wrapper_lawyer_show_restricted">
  <div class="container_lawyer_show">

    <div class="lawyer-border"</div>
    <div class="lawyer_details">
      <div class="showbox">
        <!-- <p><strong> Job Title:</strong> <%= @lawyerinfo.job_title %></p> -->



<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <h1> <%= @lawyerinfo.job_title %> </h1>
        <p><strong> PQE:</strong> <%= @lawyerinfo.pqe %> years</p>
        <p><strong> University:</strong> <%= @lawyerinfo.university %></p>
        <p><strong>Degree Classification:</strong> <%= @lawyerinfo.degree_classification %>(HONS) </p>
        <p><strong> Expected Salary:</strong> £ <%= @lawyerinfo.expected_salary %></p>
        <p><strong> Job status:</strong> <%= @lawyerinfo.job_status %></p>
        <p><strong> Practice area:</strong> <%= @lawyerinfo.practice_area %></p>
        <p><strong> Target Firm Type:</strong> <%= @lawyerinfo.firm_type %></p>
        <p><strong> Interests:</strong> <%= @lawyerinfo.interests %></p>
        <p><strong>Post Code:</strong> <%= @lawyerinfo.post_code %></p>
        <%#= cl_image_tag @lawyerinfo.cv, height: 300, width: 400, crop: :fill, format: :docx %>
      </div>
    <div class="col-xs-4">
      <%= simple_form_for(@interview) do |f| %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, "Go", class: "btn btn-primary", id: 'interview_submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/firm_infos/new.html.erb
<div class="container" style="background-image: url('<%= image_path 'background.png' %>')">
  <div class="row">
    <div class="firm-sign-up">
      <div class="col-xs-4 col-sm-4 col-md-offset-4">
          <%= simple_form_for(@firm_info) do |f| %>
          <h2 class="text-center"> Law Firm </h2>
          <h4 class="text-center">Sign Up</h4>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :firm_name %>
          <%= f.input :job_title %>
          <%= f.submit :submit %>
        <% end %>
    </div>
  </div>
  </div>
</div>

app/views/firm_infos/show.html.erb
<h1>WE MADE IT</h1>

app/views/firm_infos/update.html.erb
<h1>FirmInfos#update</h1>
<p>Find me in app/views/firm_infos/update.html.erb</p>

app/views/interviews/_form_interview.html.erb
<div class="container-interview">
  <div class="form-wrapper-interview" style="width: 400px; margin: 0 auto;">
    <h2>Book an interview</h2>

    <%= simple_form_for(@interview) do |f| %>
      <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/interviews/destroy.html.erb
<h1>Interviews#destroy</h1>
<p>Find me in app/views/interviews/destroy.html.erb</p>

app/views/interviews/edit.html.erb
<h1>Interviews#edit</h1>
<p>Find me in app/views/interviews/edit.html.erb</p>

app/views/interviews/firm_schedule.html.erb
<div class="sign-in-container" style="background-image: url('<%= image_path 'background.png' %>')">

  <h2 class="text-center"><%= current_user.firm_info.firm_name%> Recruitment Dashboard</h2>

  <div class="header-interviews">
    <div class="interviews-section">
      <h3 id="interview-heading">Interviews Scheduled</h3>
      <table class="mycontainer">
        <tbody>
          <tr>
            <th scope="col">Candidate Name</th>
            <th scope="col">Department</th>
            <th scope="col">Position</th>
            <th scope="col">Date & Time</th>
            <th scope="col">Status</th>
          </tr>
          <tr>
            <th scope="row">Ernest Shackleton</th>
            <td><p>Banking & Finance</p></td>
            <td><p>Junior Associate</p></td>
            <td><p>24th June 2018, <strong>10 am</strong></p></td>
            <td><a class="btn btn-primary main-button" id="sweet-alert-demo2">In progress</a></td>
          </tr>
          <tr>
            <th scope="row">Donald Campbell</th>
            <td><p>Litigation</p></td>
            <td><p>Junior Associate</p></td>
            <td><p>27th June 2018, <strong>1pm</strong></p></td>
            <td>
              <div class="flex-buttons">
                <a class="btn btn-primary main-button" id="confirmed"><strong>Confirmed</strong></a>
                <div class="interview-edit">
                  <button type="button" class="btn btn-primary main-button" id="reschedule-button" data-toggle="modal" data-target="#exampleModal">Reschedule</button>
                </div>
              </div>
            </td>
          </tr>
          <tr>
            <th scope="row">Falcon Scott</th>
            <td><p>Employment</p></td>
            <td><p>Mid-Level Associate</p></td>
            <td><p>23rd June 2018, <strong>9am</strong></p></td>
            <td>
            <div class="flex-buttons">
              <a class="btn btn-primary main-button" id="confirmed"><strong>Confirmed</strong></a>
                <div class="interview-edit">
                <button type="button" class="btn btn-primary main-button" id="reschedule-button" data-toggle="modal" data-target="#exampleModal">Reschedule</button>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

    <div class="header-cv">
    <div class="interviews-section">
      <h3 id="interview-heading">CV's Requested</h3>
      <table class="mycontainer">
        <tbody>
          <tr>
            <th scope="col">Candidate Name</th>
            <th scope="col">Company</th>
            <th scope="col">Position</th>
            <th scope="col">Status</th>
          </tr>
          <tr>
            <th scope="row">Ernest Shackleton</th>
            <td><p>Brown Rudnick LLP</p></td>
            <td><p>Junior Associate</p></td>
            <td><a class="btn btn-primary main-button" id="declined"><strong>Sent</strong></a></td>
          </tr>
          <tr>
            <th scope="row">Donald Campbell</th>
            <td><p>Forbes Hare LLP</p></td>
            <td><p>Junior Associate</p></td>
            <td><a class="btn btn-primary main-button" id="declined"><strong>Sent</strong></a></td>
          </tr>
          <tr>
            <th scope="row">Falcon Scott</th>
            <td><p>Farrers</p></td>
            <td><p>Junior</p></td>
            <td><a class="btn btn-primary main-button" id="declined">Declined</a></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content interview-modal">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> Edit Interview </h5>
        <h1>Linklaters</h1>
        <h3>Hi, Donald</h3>
        <p>Can we re-arrange your interview at Linklaters for either of the following dates: </p>
        <h3>New Dates and Times</h3>
        <h8>Tuesday 26/07/2018 at 10 am</h8> <br/>
        <h8>Thursday 28/07/2018 at 11 am</h8>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Back</button>
        <button type="button" class="btn btn-primary main-button" id="sweet-alert-demo3">Send Update Request</button>
      </div>
    </div>
  </div>
</div>


<div class="modal" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">CV Request</h5>
        <h1>Linklaters</h1>
        <h3>Recruiting: Junior Associates</h3>
        <p>Team: Banking and Finance - Specialising in Derivatives </p>
        <p>Salary Bracket: £90 - £110k (depending on experience)</p>
        <h3>Requested Your CV</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Reject</button>
        <button type="button" class="btn btn-primary main-button" id="sweet-alert-demo4">Accept CV Request</button>
      </div>
    </div>
  </div>
</div>

app/views/interviews/index.html.erb
<h1>Interviews#index</h1>
<p>Find me in app/views/interviews/index.html.erb</p>




<!-- SweetAlert run in here -->

app/views/interviews/new.html.erb
<%= render 'form_interview', interview: @interview %>

app/views/interviews/update.html.erb
<h1>Interviews#update</h1>
<p>Find me in app/views/interviews/update.html.erb</p>

app/views/lawyer_infos/_form.html.erb
<%= simple_form_for(@lawyerinfo) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :current_firm, collection: ["Magic circle", "Silver circle", "US firm", "Top 30 City"]%>
  <%= f.input :job_title, collection: ["Junior Associate", "Mid-Level Associate", "Senior Associate"] %>
  <%= f.input :pqe, collection: [1, 2, 3, 4, 5, 6, 7, 8, 8, 10, 11, 12, 13, 14, 15] %>
  <%= f.input :university %>
  <%= f.input :degree_classification, collection: ["1st", "2.1", "2.2"] %>
  <%= f.input :expected_salary %>
  <%= f.input :job_status, collection: ["Actively looking", "Could be tempted", "Not actively looking"] %>
  <%= f.input :practice_area, collection: ["Litigation", "Finance", "Corporate", "Employment"] %>
  <%= f.input :firm_type, collection: ["magic circle", "silver circle", "US firm", "Top 30 City"] %>
  <%= f.input :interests %>
  <%= f.input :post_code %>
  <div class="cv-input">
    <%= f.input :cv %>
    <%= f.input :cv_cache, as: :hidden %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/lawyer_infos/destroy.html.erb
<h1>LawyerInfos#destroy</h1>
<p>Find me in app/views/lawyer_infos/destroy.html.erb</p>

app/views/lawyer_infos/edit.html.erb
<h1>Editing Lawyer Info</h1>

<%= render 'form', lawyerinfo: @lawyerinfo %>

<%= link_to 'Show', @lawyerinfo %>
<%= link_to 'Back', lawyer_infos_path %>

app/views/lawyer_infos/new.html.erb
<div class="wrapper_lawyer_new">
  <div class="container_lawyer_info">
    <div class="lawyer_new_heading">
      <h1>Lawyers</h1>
      <h2>Sign Up</h2>
    </div>
    <div class="simple">
      <%= render 'form', lawyerinfo: @lawyerinfo %>
    </div>
  </div>
</div>

app/views/lawyer_infos/show.html.erb
<div class="wrapper_lawyer_show">
  <div class="container_lawyer_show">

    <div class="lawyer-border"><h1><%= @lawyerinfo.job_title %></h1></div>
    <div class="lawyer_details">
      <div class="showbox">
        <!-- personal info  -->
        <div class="sub-info">
          <p class="subheading"> <strong> Personal information </strong></p>
          <p><strong> Email: </strong> <%= @lawyerinfo.user.email %></p>
          <p><strong> First Name:</strong> <%= @lawyerinfo.first_name %></p>
          <p> <strong> Last Name:</strong> <%= @lawyerinfo.last_name %></p>
          <p><strong>Post Code:</strong> <%= @lawyerinfo.post_code %></p>
        </div>
        <!-- firm info  -->
        <div class="sub-info">
          <p class="subheading"> <strong> Firm information </strong></p>
          <p><strong> Current Firm:</strong> <%= @lawyerinfo.current_firm %></p>
          <p><strong> PQE:</strong> <%= @lawyerinfo.pqe %> years</p>
          <p><strong> Practice area:</strong> <%= @lawyerinfo.practice_area %></p>
        </div>
        <!-- uni info  -->
        <div class="sub-info">
          <p class="subheading"> <strong> University information </strong></p>
          <p><strong> University:</strong> <%= @lawyerinfo.university %></p>
          <p><strong>Degree Classification:</strong> <%= @lawyerinfo.degree_classification %>(HONS) </p>
        </div>
        <!-- Additional info -->
        <div class="sub-info">
          <p class="subheading"> <strong> Additional information </strong></p>
          <p><strong> Expected Salary:</strong> £ <%= @lawyerinfo.expected_salary %></p>
          <p><strong> Job status:</strong> <%= @lawyerinfo.job_status %></p>
          <p><strong> Target Firm Type:</strong> <%= @lawyerinfo.firm_type %></p>
          <p class="last-p"><strong> Interests:</strong> <%= @lawyerinfo.interests %></p>
        </div>
        <% if @lawyerinfo.cv.model[:cv] != nil%>
          <iframe src="http://docs.google.com/gview?url=<%= cl_image_path @lawyerinfo.cv %>&embedded=true", width="300px", height="400px"></iframe>
        <% end %>

      </div>
      <div class="buttons_lawyer_show">
        <%= link_to "Delete", lawyer_info_path(@lawyerinfo), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary custom-button" %>
        <%= link_to "Edit", edit_lawyer_info_path, class: "btn btn-primary custom-button" %>
      </div>
    </div>
  </div>
</div>

app/views/lawyer_infos/update.html.erb
<h1>LawyerInfos#update</h1>
<p>Find me in app/views/lawyer_infos/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%# image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if current_user.lawyer == true%>
        <%= link_to "Dashboard", lawyer_schedule_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "My details", lawyer_info_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to "Search", firm_infos_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Interviews", firm_schedule_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <%= link_to destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link", method: :delete do %>
         <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>

      <!-- Avatar with dropdown menu -->
      <!-- <div class="navbar-wagon-item">
        <div class="dropdown">
          <%#= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%#= t(".profile", default: "Profile") %>
              <%# end %>
            </li>
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Settings") %>
              <%# end %>
            </li>
            <li>
              <%#= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%#= t(".sign_out", default: "Log out") %>
              <%# end %>
            </li>
          </ul>
        </div>
      </div> -->
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Asap:400,500,700" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lasoo Lawyer - the new way to get a legal job</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%=  render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%# unless controller_name == "pages" %>
    <%= javascript_pack_tag 'application' %>
    <%# end %>
    <% if controller_name == "pages" %>
      <%= javascript_pack_tag 'banner' %>
    <% end %>
    <%= javascript_pack_tag 'application' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background-image-home" style="background-image: url('<%= image_path 'background2.png' %>')">
  <div class="home-headers">
    <h1>Lasoo Lawyers</h1>
    <h3>Connecting Lawyers to Law Firms <br/>
    <h3><span id="banner-typed-text"></span></h3>
    </h3>
  </div>
</div>